--ajax 학습용 테이블
CREATE TABLE CLASS_INFO (
    CLASS_CODE VARCHAR2(50) PRIMARY KEY
    , CLASS_NAME VARCHAR2(100) NOT NULL
);

CREATE TABLE STUDENT_INFO (
    STU_NUM NUMBER PRIMARY KEY
    , STU_NAME VARCHAR2(100)
    , KOR_SCORE NUMBER
    , ENG_SCORE NUMBER
    , CLASS_CODE VARCHAR2(50) REFERENCES CLASS_INFO (CLASS_CODE)
);

INSERT INTO CLASS_INFO VALUES ('101', '자바반');
INSERT INTO CLASS_INFO VALUES ('102', '캐드반');
INSERT INTO CLASS_INFO VALUES ('103', '디자인반');

INSERT INTO STUDENT_INFO VALUES (1, '김자바', 0, 0, '101');
INSERT INTO STUDENT_INFO VALUES (2, '김길동', 0, 0, '101');
INSERT INTO STUDENT_INFO VALUES (3, '김둘리', 0, 0, '101');
INSERT INTO STUDENT_INFO VALUES (4, '김꺽정', 0, 0, '101');
INSERT INTO STUDENT_INFO VALUES (5, '김유신', 0, 0, '101');

INSERT INTO STUDENT_INFO VALUES (6, '이자바', 0, 0, '101');
INSERT INTO STUDENT_INFO VALUES (7, '이길동', 0, 0, '102');
INSERT INTO STUDENT_INFO VALUES (8, '이둘리', 0, 0, '102');
INSERT INTO STUDENT_INFO VALUES (9, '이꺽정', 0, 0, '102');
INSERT INTO STUDENT_INFO VALUES (10, '이유신', 0, 0, '102');

INSERT INTO STUDENT_INFO VALUES (11, '박자바', 0, 0, '103');
INSERT INTO STUDENT_INFO VALUES (12, '박길동', 0, 0, '103');
INSERT INTO STUDENT_INFO VALUES (13, '박둘리', 0, 0, '103');
INSERT INTO STUDENT_INFO VALUES (14, '박꺽정', 0, 0, '103');
INSERT INTO STUDENT_INFO VALUES (15, '박유신', 0, 0, '103');
COMMIT;