CREATE TABLE TEST_BOARD (
    BOARD_NUM NUMBER PRIMARY KEY
    , BOARD_TITLE VARCHAR2(200) NOT NULL
    , BOARD_CONTENT VARCHAR2(500)
    , BOARD_WRITER VARCHAR2(100) NOT NULL
    , CREATE_DATE DATE DEFAULT SYSDATE
);