SELECT * FROM EMP;

CREATE OR REPLACE VIEW V_EMP
AS
SELECT EMPNO, ENAME, JOB
FROM EMP;

SELECT * FROM V_EMP;

UPDATE EMP 
SET 
ENAME = '이사랑'
WHERE EMPNO = 1001;

--모든 사원의 사원번호, 사원명, 부서번호, 부서명
CREATE OR REPLACE VIEW V_EMP2
AS
SELECT EMPNO, ENAME, EMP.DEPTNO, DNAME
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

SELECT * FROM V_EMP2;