--쇼핑몰 프로젝트 관련 테이블 --
--테이블 : 회원정보, 상품 카테고리, 상품정보, 상품이미지 정보, 장바구니, 구매정보

DROP TABLE SHOP_MEMBER;
CREATE TABLE SHOP_MEMBER (
    MEM_ID VARCHAR2(100) CONSTRAINT PK_SHOP_MEMBER PRIMARY KEY 
    , MEM_PW VARCHAR2(100) NOT NULL
    , MEM_NAME VARCHAR2(100) NOT NULL
    , MEM_TELL VARCHAR2(100) NOT NULL
    , MEM_EMAIL VARCHAR2(200)
    , MEM_ADDR VARCHAR2(300)
    , IS_ADMIN VARCHAR2(6) DEFAULT 'N' --Y, N
    , JOIN_DATE DATE DEFAULT SYSDATE
);

COMMENT ON TABLE SHOP_MEMBER IS '쇼핑몰 회원정보 테이블';
COMMENT ON COLUMN SHOP_MEMBER.MEM_ID IS '회원ID';
COMMENT ON COLUMN SHOP_MEMBER.MEM_PW IS '회원PW';

--상품 카테고리
CREATE TABLE ITEM_CATEGORY (
    --CATE_001
    CATE_CODE VARCHAR2(50) CONSTRAINT PK_ITEM_CATEGORY PRIMARY KEY
    , CATE_NAME VARCHAR2(100) NOT NULL
);

--상품정보 테이블
CREATE TABLE SHOP_ITEM (
    -- ITEM_001
    ITEM_CODE VARCHAR2(100) CONSTRAINT PK_SHOP_ITEM PRIMARY KEY
    , ITEM_NAME VARCHAR2(100) NOT NULL UNIQUE
    , ITEM_PRICE NUMBER NOT NULL
    , ITEM_DETAIL VARCHAR2(1000)
    , ITEM_STOCK NUMBER DEFAULT 10
);