--쇼핑몰 프로젝트 관련 테이블 --
--테이블 : 회원정보, 상품 카테고리, 상품정보, 상품이미지 정보, 장바구니, 구매정보

DROP TABLE SHOP_MEMBER;
CREATE TABLE SHOP_MEMBER (
    MEM_ID VARCHAR2(100) CONSTRAINT PK_SHOP_MEMBER PRIMARY KEY 
    , MEM_PW VARCHAR2(100) NOT NULL
    , MEM_NAME VARCHAR2(100) NOT NULL
    , MEM_TELL VARCHAR2(100) NOT NULL
    , MEM_EMAIL VARCHAR2(200)
    , MEM_ADDR VARCHAR2(300)
    , IS_ADMIN VARCHAR2(6) DEFAULT 'N' --Y, N
    , JOIN_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM SHOP_MEMBER;

COMMENT ON TABLE SHOP_MEMBER IS '쇼핑몰 회원정보 테이블';
COMMENT ON COLUMN SHOP_MEMBER.MEM_ID IS '회원ID';
COMMENT ON COLUMN SHOP_MEMBER.MEM_PW IS '회원PW';

--상품 카테고리
CREATE TABLE ITEM_CATEGORY (
    --CATE_001
    CATE_CODE VARCHAR2(50) CONSTRAINT PK_ITEM_CATEGORY PRIMARY KEY
    , CATE_NAME VARCHAR2(100) NOT NULL
);

INSERT INTO ITEM_CATEGORY VALUES('CATE_001', 'IT/인터넷');
INSERT INTO ITEM_CATEGORY VALUES('CATE_002', '사회/과학');
INSERT INTO ITEM_CATEGORY VALUES('CATE_003', '경제/경영');

SELECT * FROM ITEM_CATEGORY;

--메뉴 테이블
DROP TABLE ADMIN_MENU;
CREATE TABLE ADMIN_MENU (
    MENU_CODE VARCHAR2(50) PRIMARY KEY
    , MENU_NAME VARCHAR2(100) NOT NULL UNIQUE
    , MENU_URI VARCHAR2(100) NOT NULL UNIQUE
);

INSERT INTO ADMIN_MENU VALUES ('MENU_001', '상품관리', 'categoryManage');
INSERT INTO ADMIN_MENU VALUES ('MENU_002', '회원관리', 'memberList');

SELECT * FROM ADMIN_MENU;

--서브 메뉴 테이블
DROP TABLE SUB_MENU;
CREATE TABLE SUB_MENU (
    SUB_MENU_CODE VARCHAR2(50) PRIMARY KEY
    , SUB_MENU_NAME VARCHAR2(100) NOT NULL UNIQUE
    , MENU_CODE VARCHAR2(50) REFERENCES ADMIN_MENU (MENU_CODE) ON DELETE CASCADE
    , MENU_URI VARCHAR2(100) NOT NULL UNIQUE
);

INSERT INTO SUB_MENU VALUES ('SUB_MENU_001', '카테고리관리', 'MENU_001', 'categoryManage');
INSERT INTO SUB_MENU VALUES ('SUB_MENU_002', '상품등록', 'MENU_001', 'regItem');
INSERT INTO SUB_MENU VALUES ('SUB_MENU_003', '상품관리', 'MENU_001', 'itemManage');
INSERT INTO SUB_MENU VALUES ('SUB_MENU_004', '회원목록', 'MENU_002', 'memberList');

UPDATE SUB_MENU
SET SUB_MENU_NAME = '상품관리'
WHERE SUB_MENU_CODE = 'SUB_MENU_003';

SELECT * FROM SUB_MENU;
--상품정보 테이블
CREATE TABLE SHOP_ITEM (
    -- ITEM_001
    ITEM_CODE VARCHAR2(100) CONSTRAINT PK_SHOP_ITEM PRIMARY KEY
    , ITEM_NAME VARCHAR2(100) NOT NULL UNIQUE
    , ITEM_PRICE NUMBER NOT NULL
    , ITEM_DETAIL VARCHAR2(1000)
    , ITEM_STOCK NUMBER DEFAULT 10
    , CATE_CODE VARCHAR2(50) REFERENCES ITEM_CATEGORY (CATE_CODE) ON DELETE CASCADE
);

--상품 이미지 정보 테이블
DROP TABLE ITEM_IMAGE;
CREATE TABLE ITEM_IMAGE (
    IMG_CODE NUMBER PRIMARY KEY --1, 2, 3...
    , ORIGIN_IMG_NAME VARCHAR2(200) --원본 파일명
    , ATTACHED_IMG_NAME VARCHAR2(200) --첨부된 파일명
    , IS_MAIN VARCHAR2(10) --대표 이미지 여부 'Y', 'N'
    , ITEM_CODE VARCHAR2(100) REFERENCES SHOP_ITEM (ITEM_CODE) ON DELETE CASCADE
);

SELECT * FROM SHOP_MEMBER;

UPDATE SHOP_MEMBER
SET
IS_ADMIN = 'Y'
WHERE MEM_ID = 'admin';

--ITEM_001
--ITEM_002 -> ITEM_003
--TO_NUMBER(SUBSTR(ITEM_CODE, 6)) ->  1, 2
--NVL(, ), LPAD(값, 자릿수, 채워줄 문자)

SELECT 'ITEM_'||LPAD(NVL(MAX(TO_NUMBER(SUBSTR(ITEM_CODE, 6))), 0) + 1, 3, 0)
FROM SHOP_ITEM;

SELECT NVL(MAX(IMG_CODE), 0) + 1
FROM ITEM_IMAGE;

DELETE ITEM_IMAGE;
DELETE SHOP_ITEM;

SELECT * FROM SHOP_ITEM; --1
SELECT * FROM ITEM_IMAGE; --3

--상품명, 가격, 첨부된 파일명
SELECT SHOP_ITEM.ITEM_CODE
    , ITEM_NAME
    , ITEM_PRICE
    , ATTACHED_IMG_NAME
FROM SHOP_ITEM , ITEM_IMAGE
WHERE SHOP_ITEM.ITEM_CODE = ITEM_IMAGE.ITEM_CODE
AND IS_MAIN = 'Y';

SELECT ITEM.ITEM_CODE
    , ITEM_NAME
    , ITEM_PRICE
    , ITEM_DETAIL
    , ATTACHED_IMG_NAME
FROM SHOP_ITEM ITEM, ITEM_IMAGE IMG
WHERE ITEM.ITEM_CODE = IMG.ITEM_CODE;

--장바구니 테이블
DROP TABLE SHOP_CART;
CREATE TABLE SHOP_CART (
    --상품명, 가격
    CART_NUM NUMBER PRIMARY KEY 
    , ITEM_CODE VARCHAR2(100) REFERENCES SHOP_ITEM (ITEM_CODE) NOT NULL 
    , MEM_ID VARCHAR2(100) REFERENCES SHOP_MEMBER (MEM_ID) NOT NULL
    , ITEM_CNT NUMBER NOT NULL 
    , CREATE_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM SHOP_CART;
DELETE SHOP_CART;

--상품 이미지명, 상품명, 가격, 수량, 총가격
SELECT ITEM.ITEM_NAME
    , ITEM.ITEM_PRICE
    , CART.ITEM_CNT
    , ITEM.ITEM_PRICE * CART.ITEM_CNT AS TOTAL_PRICE
    , ATTACHED_IMG_NAME
FROM SHOP_ITEM ITEM, SHOP_CART CART, ITEM_IMAGE IMG
WHERE ITEM.ITEM_CODE = CART.ITEM_CODE
AND CART.ITEM_CODE = IMG.ITEM_CODE
AND CART.MEM_ID = 'admin'
AND IMG.IS_MAIN = 'Y';

SELECT 
    (SELECT ITEM_NAME 
    FROM SHOP_ITEM 
    WHERE ITEM_CODE  = SHOP_CART.ITEM_CODE) AS ITEM_NAME
    , (SELECT ITEM_PRICE
        FROM SHOP_ITEM
        WHERE ITEM_CODE = SHOP_CART.ITEM_CODE) AS ITEM_PRICE
    , ITEM_CNT
    , (SELECT ITEM_PRICE 
        FROM SHOP_ITEM
        WHERE ITEM_CODE = SHOP_CART.ITEM_CODE) * ITEM_CNT AS TOTAL_PRICE
    , (SELECT ATTACHED_IMG_NAME
        FROM ITEM_IMAGE
        WHERE ITEM_CODE = SHOP_CART.ITEM_CODE
        AND IS_MAIN = 'Y') AS ATTACHED_IMG_NAME
FROM SHOP_CART;

GRANT CREATE VIEW TO MYDB;

--0328
--장바구니번호, 상품코드, 상품명, 가격, 상품대표이미지
--총가격, 장바구니 회원 ID, 장바구니에 들어간 개수, 날짜
--DROP VIEW ART_VIEW;
CREATE OR REPLACE VIEW CART_VIEW
AS
SELECT CART.CART_NUM
    , CART.ITEM_CODE
    , ITEM.ITEM_NAME
    , ITEM.ITEM_PRICE
    , ITEM.ITEM_PRICE * CART.ITEM_CNT AS TOTAL_PRICE
    , CART.ITEM_CNT
    , TO_CHAR(CREATE_DATE, 'YYYY-MM-DD') AS CREATE_DATE
    , CART.MEM_ID
    , IMG.ATTACHED_IMG_NAME
FROM SHOP_CART CART, SHOP_ITEM ITEM, ITEM_IMAGE IMG 
WHERE CART.ITEM_CODE = ITEM.ITEM_CODE
AND CART.ITEM_CODE = IMG.ITEM_CODE
AND IMG.IS_MAIN = 'Y';

SELECT * FROM CART_VIEW
WHERE MEM_ID = 'admin';

SELECT SUM(TOTAL_PRICE)
FROM CART_VIEW
WHERE MEM_ID = 'admin';

SELECT * FROM SHOP_CART;

--0331
--구매정보 테이블
CREATE TABLE SHOP_BUY (
    BUY_NUM NUMBER PRIMARY KEY
    , MEM_ID VARCHAR2(100) REFERENCES SHOP_MEMBER (MEM_ID)
    , ITEM_CODE VARCHAR2(100) REFERENCES SHOP_ITEM (ITEM_CODE)
    , ITEM_CNT NUMBER 
    , BUY_PRICE NUMBER
    , BUY_DATE DATE DEFAULT SYSDATE
    , ORDER_NUM VARCHAR2(100) --주문날짜_주문자ID 20220331101010_admin
);

SELECT * FROM SHOP_BUY;
























