CREATE TABLE SECURE_MEMBER (
    MEM_ID VARCHAR2(100) PRIMARY KEY
    , MEM_PW VARCHAR2(500)
    , MEM_EMAIL VARCHAR2(100)
    , JOIN_DATE DATE DEFAULT SYSDATE
    , MODIFY_DATE DATE
);
select * from SECURE_MEMBER;

drop table MEMBER_ROLE;
CREATE TABLE MEMBER_ROLE (
    ID NUMBER PRIMARY KEY
    , MEM_ID VARCHAR2(100)
    , ROLE_NAME VARCHAR2(30)
);

INSERT INTO MEMBER_ROLE VALUES (1, 'admin', 'ROLE_USER');
INSERT INTO MEMBER_ROLE VALUES (2, 'admin', 'ROLE_ADMIN');
INSERT INTO MEMBER_ROLE VALUES (3, 'java', 'ROLE_USER');