--1.
ALTER SESSION SET "_ORACLE_SCRIPT" = true;
CREATE USER BOOKSHELF IDENTIFIED BY book;
GRANT CONNECT, RESOURCE, CREATE VIEW TO BOOKSHELF;
ALTER USER BOOKSHELF DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;


